snyk

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,33 +1,71 @@
-# This is a basic workflow to help you get started with Actions
+--- # ---
 
-name: docker-build
+# # This is a basic workflow to help you get started with Actions
+
+# name: docker-build
+# on:
+#   push:
+#     branches:
+#       - 'master'
+# jobs:
+#   build:
+#     runs-on: ubuntu-latest
+
+#     steps:
+#       -
+#         name: Checkout
+#         uses: actions/checkout@v2
+#       -
+#         name: Login to Docker Hub
+#         uses: docker/login-action@v1
+#         with:
+#           username: ${{ secrets.DOCKER_HUB_USERNAME }}
+#           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
+#       -
+#         name: Set up Docker Buildx
+#         uses: docker/setup-buildx-action@v1
+#       -
+#         name: Build and push
+#         uses: docker/build-push-action@v2
+#         with:
+#           context: .
+#           file: ./Dockerfile
+#           push: true
+#           tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.APP_NAME }}:latest
+name: Snyk SCA, Code, IaC and Container CLI monitor example
 on:
   push:
-    branches:
-      - 'master'
+    branches: [master]
+  pull_request:
+    branches: [master]
+
 jobs:
   build:
+    name: Test and build
+    environment: snyk-npm
     runs-on: ubuntu-latest
-
     steps:
-      -
-        name: Checkout 
-        uses: actions/checkout@v2
+      - name: Setup Snyk + snyk-to-html
+        run: |
+          npm install snyk -g
+          npm install snyk-to-html -g
+          snyk auth ${{secrets.SNYK_TOKEN}
+      - name: Snyk Open Source # For testing and failing please add snyk test before snyk cmonitor
+        run: |
+          snyk monitor
+      - name: Snyk Code # Remove || true to fail if there are vulnerabilities
+        run: |
+          snyk code test || true
+      - name: Snyk Container # Rename your image, for testing and failing please add snyk container test before snyk container monitor
+        run: |
+          docker build . -t {{ secrets.APP_NAME }}:latest
+           snyk container monitor yourimage:tag --file=Dockerfile
+      - name: Snyk IaC # Remove || true to fail if there are vulnerabilities
+        run: |
+          snyk iac test || true
       -
         name: Login to Docker Hub
         uses: docker/login-action@v1
         with:
           username: ${{ secrets.DOCKER_HUB_USERNAME }}
           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
-      -
-        name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1
-      -
-        name: Build and push
-        uses: docker/build-push-action@v2
-        with:
-          context: .
-          file: ./Dockerfile
-          push: true
-          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.APP_NAME }}:latest
-
